### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by d-513** [SocketByte/MinecraftServerNetwork#11]
Will there be 1.16 support or an actual documentation

**Comment by d-513** [comment]
It seems to work on that version well, but I'm a bit confused with the coordinates

**Comment by SocketByte** [comment]
Hey!
Would love to work a little bit more on my opensrc projects but currently I'm really busy. MSN is a really complicated project that takes a lot of time and effort to develop, but maybe I'll be able to come back to it in the future. Sorry!

**Comment by SocketByte** [comment]
> It seems to work on that version well, but I'm a bit confused with the coordinates

What do you mean exactly? Maybe Ill be able to help.

**Comment by d-513** [comment]
I think it was my setup, I got them to work

**Comment by d-513** [comment]
Now the only bug is that entities don't seem to be transferred over sectors, for example, if someone had a sheep on a lead or a zombie was following that person it wouldn't go to the other sector, but other than that thank you its an excellent plugin!
