### ISSUE TITLE
Can only go through a sector using its corner

### ISSUE THREAD

**Issue by d-513** [SocketByte/MinecraftServerNetwork#12]
A video showcasing the issue: https://i.d513.space/SSfU5O8fZx.mp4
Config file: https://haste.d513.space/icufotureg.yaml

**Comment by sadcenter** [comment]
i think its your config issue 
https://github.com/oski646/sectors-generator
(values from your config)
![image](https://user-images.githubusercontent.com/55924469/103443590-199a1880-4c61-11eb-80d9-83d3e15bfa3c.png)

https://www.mediafire.com/file/egj9onvpngt0unj/test.html/file
