### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by durajg01** [SocketByte/MinecraftServerNetwork#8]
Can you get some instructions on how to install it?

**Comment by SocketByte** [comment]
It's currently WIP, but it (mostly) works fine for testing, you can download the latest build from the Releases tab, NetworkProxy goes onto your bungee server, and NetworkClient on your spigot instances (remember to enable `bungeecord: true` in your spigot.yml file). Then configure the proxy, and you should be good to go. (Of course for the best results, each spigot instance should have the same plugins and world files) Remember that it works on Redis pub/sub system, so you need to have a redis server somewhere too. In the future there will be more detailed info on how to install the MSN, but well, not yet, I have other (also commercial) projects as well, so idk when that would be. Hope I was useful.

PS: Also keep in mind that it currently works only on 1.9+ versions.

**Comment by durajg01** [comment]
Mhmm, thanks

**Comment by durajg01** [comment]
Do I need Redisbungee for this?

**Comment by SocketByte** [comment]
Nope, you need a redis server running somewhere. Might be localhost on windows, might be on a dedicated server. Doesn't matter, as long as you can connect to it.

**Comment by durajg01** [comment]
Thanks :D
