### ISSUE TITLE
Problem z połączeniem

### ISSUE THREAD

**Issue by durajg01** [SocketByte/MinecraftServerNetwork#9]
Witam serdecznie, mam problem z połączaniem serwera spigot,
odpalam normalnie serwer redis na Windowsie i BungeeCord łączy się normalnie, ale już spigot ma taki o błąd wersja 1.8.8 https://prnt.sc/shbz5n

**Comment by loperd** [comment]
Problem with connect to redis, see to Redis. It looks like a Redis server is not working.
